--19-MAY-25
--CURSORES SENCILLOS - MANUALMENTE
use northwind

go

DECLARE EMPLEADOS CURSOR SCROLL FOR
    SELECT * FROM EMPLOYEES

OPEN EMPLEADOS

--CAMBIA LA FILA DE LOS EMPLEADOS CADA QUE SE EJECUTA
FETCH NEXT FROM EMPLEADOS

--SI YA RECORRIO TODAS LAS FILAS
SELECT @@FETCH_STATUS

--SE DESIGNO DE TIPO SCROLL, LO CUAL HACE QUE REGRESE
FETCH PRIOR FROM EMPLEADOS

--RECUPERA LA FILA 5 (SU ID)
FETCH ABSOLUTE 5 FROM EMPLEADOS

--COMO ESTABA EN EL 5 AHORA TE DA EL 3, YA QUE SON 2 MENOS
FETCH RELATIVE -2 FROM EMPLEADOS

--COMO ESTABA EN EL 3 AHORA TE DA 5, YA SUMA 2 
FETCH RELATIVE 2 FROM EMPLEADOS

--IMPORTANTE CERRAR, PARA QUE PUEDA SEGUIR OTROS PROCESOS (LIBERAR LA MEMORIA)
CLOSE EMPLEADOS
DEALLOCATE EMPLEADOS

GO



--PROCEDIMIENTO ALMACENADO
CREATE PROC REPORTEORDENES
AS   

DECLARE EMPLEADOS CURSOR SCROLL FOR
    SELECT EmployeeID FROM EMPLOYEES

DECLARE @EID INT 
OPEN EMPLEADOS

FETCH NEXT FROM EMPLEADOS INTO @EID

WHILE @@FETCH_STATUS = 0
    BEGIN
        --MUESTRA CUANTAS ORDENES COLOCO
        SELECT COUNT (*) FROM ORDERS WHERE EMPLOYEEID = @EID
        FETCH NEXT FROM EMPLEADOS INTO @EID
    END

CLOSE EMPLEADOS
DEALLOCATE EMPLEADOS

GO

--PARA OLVIDAR EL PROCEDIMIENTO
--DROP PROC REPORTEORDENES

--EJECUTA EL REPORTE
EXEC REPORTEORDENES

